### ISSUE TITLE
Are you getting DDoS protection by Cloudflare page in your response?

### ISSUE THREAD

**Issue by LindaTNguyen** [fhightower/robtex-python#2]
* Robtex Python version:1.0.0
* Python version: python3 
* Operating System: Ubuntu v16

### Description
I'm trying to call the robtex_python.ip_query(<ip_address>) and I'm getting back a page response that has the DDoS protection by Cloudflare page.  This is for any given IP address. I also tried to call the page directly using requests.get('https://freeapi.robtex.com/ipquery/<ip_address>/") and I get the same results.  I am trying to call the free API to get back json data and have not been successful.  Although I have no problems hitting the url manually via my browser.

### What I Did
Added this line in my code:
response = robtex_python.ip_query(<any_ip_address>)

response.ok returns False
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by fhightower** [comment]
Interesting, I'm unable to replicate this issue as the `robtex_python.ip_query()` function is working properly for me. Have you been making a lot of requests to the API? If you're using the [free Robtex API](https://www.robtex.com/api/#free_api), my guess is that Robtex has rate-limited you.

Try again in the next few days and see if you are still getting this error.

**Comment by LindaTNguyen** [comment]
I hadn't made the call for 24 hrs. and went back today to try to call it with same results.  To test it, I set the ip variable to  '58.158.177.102' and called robtex_python.ip_query(ip)
Debugging this,  I was able to see that the api_path variable passed into requester.get(api_path) is  'https://freeapi.robtex.com/ipquery/58.158.177.102'.. Can you confirm that is the correct format?

Would you mind copying what test value you're using and how you're calling it?

Thanks,
Linda

**Comment by fhightower** [comment]
Sorry it's taken me so long to reply.

Yes, `https://freeapi.robtex.com/ipquery/58.158.177.102` is the correct format. In fact, try to visit https://freeapi.robtex.com/ipquery/58.158.177.102 in your browser and see if you get a json response or get blocked by cloudflare.

To test this in python, I'm using:

```python
import robtex_python

print(robtex_python.ip_query("<IP ADDRESS>"))
```

**Comment by LindaTNguyen** [comment]
I think Robtex has blacklisted the IP from my office as I was able to get it working from home.  Thanks for your help!
